version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    app:
        container_name: app
        build:
            context: ./infra/app
            dockerfile: Dockerfile
        image: php-laravel-7.0
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    db:
        container_name: pgsql
        image: postgres:14.1-alpine
        restart: unless-stopped
        expose:
            - "5432"
        ports:
            - "5432:5432"
        volumes:
            - ./infra/pgsql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - app-network

    nginx:
        image: nginx:1.19.8-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8100:80
        volumes:
            - ./:/var/www
            - ./infra/nginx/conf:/etc/nginx/conf.d
        networks:
            - app-network
